services:
  node:
    image: node:22
    user: node
    working_dir: /home/node
    command: tail -f /dev/null
    ports:
      - 3000-3009:3000-3009
    volumes:
      - ../apeframework:/home/node/apeframework
      - ../apeframework-eslint:/home/node/apeframework-eslint
